name: Template Git Integration
permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      commitData:
        description: 'Commit data in JSON format'
        required: true

jobs:
  update-templates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Decode commit data
        run: |
          cat <<"TAGTEXTFILE" > commit_info.json
          ${{ github.event.inputs.commitData }}
          TAGTEXTFILE

      - name: Process commit info
        run: |
          COMMIT_MESSAGE=$(jq -r '.message' commit_info.json)
          COMMIT_PATH=$(jq -r '.path' commit_info.json)
          COMMIT_TYPE=$(jq -r '.type' commit_info.json)
          TEMPLATE=$(jq -r '.template' commit_info.json)
          DESCRIPTION=$(jq -r '.description' commit_info.json)

          if [ "$COMMIT_TYPE" == "2" ]; then
            echo "Deleting $COMMIT_PATH"
            rm "$COMMIT_PATH"
            git rm "$COMMIT_PATH"
          else
            echo "Writing to $COMMIT_PATH"
            echo "$TEMPLATE" > "$COMMIT_PATH"
            git add "$COMMIT_PATH"
          fi

          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -m "${DESCRIPTION:-$COMMIT_MESSAGE}"
          git push
